---
title: "Práct"
subtitle: "Tratamiento de Datos, Grado en Ciencia de Datos - UV"
author: "Sergi Albuixech" # añadiros 
date:  "`r Sys.Date()`"  # 31/03/2025
output:
  html_document:
    echo: yes
    number_sections: no
    theme: lumen
    toc: yes
  pdf_document:
    toc: yes
    toc_depth: 3
    number_sections: no
---

```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# CONFIGURACIÓN GENERAL
library(knitr)
options(width = 100)
# Opciones generales chunks
opts_chunk$set(echo = T, message = F, error = F, warning = F,
               comment = NA, fig.align = 'center', dpi = 100, tidy = F,
               cache.path = '.cache/', fig.path = './figure/')
# options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
# knit_hooks$set(plot = knitr:::hook_plot_html)
knitr::opts_chunk$set(fig.width=8, fig.height=4)
```

```{r eval = FALSE, include = FALSE}
# Especificamos las librerías necesarias en esta lista
packages = c("tidyverse", "knitr", "ggplot2", "datasets", "RColorBrewer","nycflights13")
# use this function to check if each package is on the local machine
# if a package is installed, it will be loaded
# if any are not, the missing package(s) will be installed and loaded
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE,repos='http://cran.rediris.es')
    library(x, character.only = TRUE)
  }
})
# verify they are loaded
search()
```

## Introducción y objetivos.
El objetivo de este proyecto(hacer introduccion) 

## Load libraries, functions, and data files

```{r, message = FALSE, warning = FALSE}
# vis
library('ggplot2') # visualization


# wrangle
library('dplyr') # data manipulation
library('tidyr') # data manipulation
library('readr') # data input
library('stringr') # string manipulation
library('forcats') # factor manipulation
library('modelr') # factor manipulation




#Libreria PDF 
library(pdftools)


```





